version: '3'

services:
  fastapi:
    image: 245796545339.dkr.ecr.ap-northeast-1.amazonaws.com/study02-fastapi
    build:
      dockerfile: ./scripts/fastapi/Dockerfile
      context: ./
      args:
        - IMAGE_TAG=${IMAGE_TAG}